language: objective-c

osx_image: xcode7.1

before_install:
  - gem install cocoapods

script:
# Fails with "Unable to find Analytics/TestFlight".
# - pod lib lint --allow-warnings
  - cd Example && pod install
  - cd .. && make xctest

notifications:
  email: false
